version: '3.9'
services:
  app:
    image: app-coding-dojo
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_PROFILES_ACTIVE: prod
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5