version: '3.9'
services:
  app:
    image: app-coding-dojo
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    restart: always
  db:
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password