logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.hibernate: ERROR
    com.assignment.spring: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

weather:
  api:
    url: "http://api.openweathermap.org/data/2.5/weather?q={city}&appid={appid}"
    token: "1f22d69855855e0ff5c7e8114de4f393"
  cache:
    expireAfterWriteInSeconds: 10
